processed_dir: "./datas/lastfm-processed/"

raw:
  path: "./datas/hetrec2011-lastfm-2k/user_artists.dat"
  sep: "\t"
  has_header: true
  user_col: 0
  item_col: 1
  rating_col: 2

split:
  seed: 42
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  min_user_interactions: 10
