processed_dir: "./datas/movieLens-100k-processed/"

raw:
  path: "./datas/ml-latest-small/ratings.csv"
  sep: ","
  has_header: true
  user_col: 0
  item_col: 1
  rating_col: 2

split:
  seed: 42
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  min_user_interactions: 10
