data:
  dataset: "lastfm"
  processed_dir: "./datas/lastfm-processed"
  batch_size: 512
  num_workers: 4
  num_negatives: 1

model:
  model_name: "lightgcn"
  embed_dim: 64
  num_layers: 3
  num_fold: 100
  dropout_flag: true
  dropout_rate: 0.05
  reg_ratio: 0.0001
  topk: [10, 20]

optim:
  optimizer: "adam"
  lr: 0.001
  weight_decay: 1e-6

train:
  seed: 42
  ckpt_root: "./ckpts/"
  max_epochs: 1000
  monitor: "val/Recall@20"
  early_stop_delta: 0.0
  early_stop_patience: 3
  save_epoch_interval: 100
  val_epoch_interval: 20
  accelerator: "auto"
  devices: "auto"
