seed: 42

data:
  processed_dir: "./datas/lastfm-processed"
  batch_size: 512
  num_workers: 4
  num_negatives: 1

model:
  embed_dim: 64
  num_layers: 3
  num_fold: 100
  dropout_flag: true
  dropout_rate: 0.1
  reg_ratio: 0.001
  topk: [10, 20]

optim:
  optimizer: "adam"
  lr: 0.001
  weight_decay: 1e-6

trainer:
  max_epochs: 200
  check_val_every_n_epoch: 5
  every_n_epochs: 10
  monitor: "val/Recall@20"
  precision: "32-true"
  ckpt_root: "./ckpts/"
  log_every_n_steps: 50
  accelerator: "auto"
  devices: "auto"
