seed: 42

data:
  processed_dir: "./datas/gowalla-processed"
  batch_size: 12800
  num_workers: 32
  num_negatives: 1

model:
  embed_dim: 128
  num_layers: 3
  num_fold: 200
  dropout_flag: true
  dropout_rate: 0.1
  reg_ratio: 0.001
  user_batch_size: 1024
  topk: [10, 20]

optim:
  optimizer: "adam"
  lr: 0.0001
  weight_decay: 1e-6

trainer:
  max_epochs: 200
  check_val_every_n_epoch: 5
  every_n_epochs: 10
  monitor: "val/Recall@20"
  precision: "32-true"
  ckpt_root: "./ckpts/"
  log_every_n_steps: 50
  accelerator: "auto"
  devices: "auto"
